name: Cleanup Cloud Resources
env:
  GO_VERSION: 1.22.8
on:
  schedule:
    - cron: "0 */3 * * *"

permissions: read-all

jobs:
  eks-cleanup:
    runs-on: ubuntu-latest
    if: ${{ vars.AWS_ROLE != '' }}
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    env:
        AWS_REGION: us-east-2
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup go
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Cleanup EKS resources
        run: |
          cd ./tools/eks-cleanup && go run .
