name: Inspektor Gadget Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update new version in krew-index
      if: github.repository == 'inspektor-gadget/inspektor-gadget'
      uses: rajatjindal/krew-release-bot@v0.0.46
      with:
        workdir: /home/runner/work/inspektor-gadget/inspektor-gadget
        krew_template_file: .krew.yaml
    - name: Update gadgets' version on artifact hub
      id: bump_gadgets
      if: github.repository == 'inspektor-gadget/inspektor-gadget'
      run: |
        # Get the version without the "v" prefix
        inspektor_gadget_version=$(echo $GITHUB_REF_NAME | tr -d '"v')

        echo "version=${inspektor_gadget_version}" >> $GITHUB_OUTPUT

        for PKGFILE in $(find gadgets/ -name artifacthub-pkg.yml) ; do
            sed -i \
                -e "s/^version:.*$/version: ${inspektor_gadget_version}/" \
                $PKGFILE
        done

        # The following is to support multiline with GITHUB_OUTPUT, see:
        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
        echo "changes<<EOF" >> $GITHUB_OUTPUT
        echo "$(git status --porcelain)" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    - name: Create PR
      if: ${{ steps.bump_gadgets.outputs.changes != '' }}
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Artifact Hub: Update gadgets version to v${{ steps.bump_gadgets.outputs.version }}'
        branch: 'auto_bump_gadgets_v${{ steps.bump_gadgets.outputs.version }}'
        base: main
        delete-branch: true
        title: 'Artifact Hub: Update gadgets version to v${{ steps.bump_gadgets.outputs.version }}'
        body: |
          Hi.

          We released a new version of Inspektor Gadget [v${{ steps.bump_gadgets.outputs.version }}](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.bump_gadgets.outputs.version }}), so the [official gadgets on Artifact Hub](https://artifacthub.io/packages/search?repo=gadgets) needs to be updated.

          This PR was automatically generated by a CI job:
          * [update-inspektor-gadget-release.yaml](https://github.com/${{ github.repository }}/blob/main/.github/workflows/release.yml)

          This PR will not be automatically merged. Please review, edit and merge as appropriate.

          Checklist:
          - [ ] Check that the [Inspektor Gadget CI](https://github.com/${{ github.repository }}/actions/workflows/inspektor-gadget.yml) completed successfully.
          - [ ] Check that the gadgets OCI images have a new tag with the correct version (v${{ steps.bump_gadgets.outputs.version }}). For example, [gadget/trace_open](https://github.com/${{ github.repository }}/pkgs/container/gadget%2Ftrace_open).
          - [ ] Check the diff of this PR.

          After merging, the Artifact Hub bot will notice the update. It might take 30 minutes.
          Then, the following will be updated:
          https://artifacthub.io/packages/search?repo=gadgets

          In case of problems, please check the logs in the [Artifact Hub control panel](https://artifacthub.io/control-panel).

          Best regards.
